version: "3.4"

services:
  todoapi:
    depends_on:
      - "postgres"
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres;port=5432;database=tododb;username=todouser;password=todouser"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
      - ./postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todouser
      POSTGRES_DB: tododb
    